name: lumora
description: Lumora App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"



dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  calendar_date_picker2: ^2.0.1

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.8
  material_symbols_icons: ^4.0.0
  font_awesome_flutter: ^10.0.0

  flutter_svg: ^2.2.3
  intl: ^0.20.2
  http: ^1.2.1

  firebase_core: ^4.0.0
  firebase_auth: ^6.1.3
  firebase_app_check: ^0.4.0+1
  google_sign_in: ^6.1.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  flutter_dotenv: ^6.0.0
 
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter



flutter: 
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

  assets:
    - assets/images/logo.png
    - assets/images/kuisioner-1.png
    - assets/images/kuisioner-2.png
    - assets/images/kuisioner-3.png
    - assets/images/kuisioner-4.png
    - assets/images/ayam.png
    - assets/images/biji.png
    - assets/images/sayur.png
    - assets/images/pisang.png
    - assets/images/baby-homepage.png
    - assets/images/gizi-bad.png
    - assets/images/gizi-good.png
    - assets/images/gizi-lamp.png
    - assets/images/info-kes-doll.png
    - assets/images/info-kes-milk.png
    - assets/images/kentang.png
    - assets/images/profildummy.png
    - assets/images/analisis-good.png
    - assets/images/analisis-bad.png
    - assets/images/bayi-nextstep.png

    - assets/icons/home.svg
    - assets/icons/milestone.svg
    - assets/icons/stimulasi.svg
    - assets/icons/star.svg
    - assets/icons/google.svg
    - assets/icons/feet.svg
    - assets/icons/growbaby-feet.svg
    - assets/icons/growbaby-star.svg
    - assets/icons/growbaby-world.svg
    - assets/icons/home-lamp.svg
    - assets/icons/nutriguide-lamp.svg
    - assets/icons/nutriguide-warning.svg
    - assets/icons/nutriguide-checklist.svg
    - assets/icons/analisis-warning.svg
    - assets/icons/baby.svg
    - assets/icons/calendar.svg
    - assets/icons/lingkar-kepala.svg
    - assets/icons/injection.svg
    - assets/icons/bb.svg
    - assets/icons/gender.svg
    - assets/icons/pin.svg
    - assets/icons/tb.svg
    - assets/icons/stimulasi-lamp.svg
    - assets/icons/stimulasi-time.svg
    - assets/icons/slim-lamp.svg


